apps/users/urls.py
from django.conf.urls import url
from users.views import LoginView, RegisterView, MyJDView

urlpatterns = [
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^myJD/(?P<user_id>\d+)/$', MyJDView.as_view(), name='myJD'),

]

jd/urls.py
import xadmin

from django.conf.urls import url, include
from django.contrib import admin
from apps.projects.views import IndexView
from apps.users import urls as user_urls
from users.views import ajax_val
from operations.views import search
from projects import urls as project_urls
from jd.settings import MEDIA_ROOT
from django.views.static import serve


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^user/', include(user_urls, namespace='user')),
    # 商品
    url(r'^product/', include(project_urls, namespace='product')),

    url(r'^xadmin/', xadmin.site.urls),
    url(r'^admin/', admin.site.urls),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),
    # 验证码动态验证
    url('^ajax_val/',ajax_val, name='ajax_val'),
    url('^search/(?P<search_field>\w{0,20})/$', search, name='search'),
    # 处理媒体文件图片
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

]

extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.rel, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str if six.PY3 else basestring
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str if six.PY3 else basestring
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):
        return super(DetailAdminView, self).get_media() + self.form_obj.media + \
            self.vendor('xadmin.page.form.js', 'xadmin.form.css')

    @filter_hook
    def get_field_result(self, field_name):

templates/login.html
<!--作者：崔然-->
<!DOCTYPE html>
<html lang="zh-cn">
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <title>京东-欢迎登陆</title>
    <link rel="icon" href="{% static "images/public/favicon.ico" %}" mce_href="{% static "images/public/favicon.ico" %}" type="image/x-icon">
    <link href="{% static "css/reset.css" %}" rel="stylesheet">
    <link href="{% static "css/logoin.css" %}" rel="stylesheet">
{#    <script src="{% static "js/jquery/jquery-1.11.3.min.js" %}"></script>#}
    <script src="{% static "js/login.js" %}"></script>
</head>



<body>

    <div id="header">
        <a href="{% static "http://www.jd.com/" %}">
            <img src="{% static "images/logo-in/logo-201305-b.png" %}">
        </a>
        <img class="img2" src="{% static "images/logo-in/l-icon.png" %}">
    </div>
    <div id="main">
        <div class="main-bg"></div>
        <div class="register">
            <div class="contain">
                <span class="vip">京东会员</span>
                <a class="zhuce" href="https://reg.jd.com/reg/person?ReturnUrl=http%3A%2F%2Fwww.jd.com" target="_blank">
                    <em></em>
                    <span>立即注册</span>
                </a>
                <div class="advice1">
                    <em></em>
                    <span id="tip">公共场所不建议自动登录，以防账号丢失</span>
                </div>
                <div class="advice2">
                    <em></em>
                    <span>请输入账户名</span>
                </div>
                <div class="advice3">
                    <em></em>
                    <span>请输入密码</span>
                </div>
                <div class="advice4" {% if login_form.errors or msg %}style="display: block;"{% endif %}>
                    <em></em>
                    <span>{{ login_form.first_error|default_if_none:'' }}{{ msg|default_if_none:'' }}</span>
                </div>
                <form id="myform" action="" method="post">
                    <div class="text" {% if login_form.errors.username %}style="border-color: rgb(228, 57, 60);"{% endif %}>
                        <em></em>
                        <input id="userName" type="text" name="username" placeholder="邮箱/用户名/已验证手机">
                    </div>
                    <div class="keywords" {% if login_form.errors.password %}style="border-color: rgb(228, 57, 60);"{% endif %}>
                        <em></em>
                        <input id="passWord" type="password" name="password" placeholder="密码">
                    </div>
                    <input class="check1" type="checkbox" checked="checked"><span class="check2">自动登录</span>
                    <a class="forget" href="{% static "http://safe.jd.com/findPwd/index.action" %}" target="_blank">忘记密码?</a>
                    <input type="submit" class="sub" >登录</input>
                    {% csrf_token %}
                </form>
            </div>
            <div class="regi-foot">
                <div class="refol fl">
                    <span>使用合作网站账号登陆京东:</span>
                    <ul>
                        <li><a>京东钱包</a><i>|</i></li>
                        <li><a>QQ</a><i>|</i></li>
                        <li><a>微信</a></li>
                    </ul>
                </div>
                <div class="refor fr"></div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="question">
            <a class="question-href" href="http://surveys.jd.com/index.php?r=survey/index/sid/568245/lang/zh-Hans" target="_blank">
                <span></span>
                <p>登录页面，调查问卷</p>
            </a>
        </div>
        <div class="foot">
            <div class="links">
                <a target="_blank" href="{% static "http://www.jd.com/intro/about.aspx" %}">
	                关于我们
	            </a> |
                <a target="_blank" href="{% static "http://www.jd.com/contact/" %}">
	                联系我们
	            </a> |
                <a target="_blank" href="{% static "http://zhaopin.jd.com/" %}">
	                人才招聘
	            </a> |
                <a target="_blank" href="{% static "http://www.jd.com/contact/joinin.aspx" %}">
	                商家入驻
	            </a> |
                <a target="_blank" href="{% static "http://www.jd.com/intro/service.aspx" %}">
	                广告服务
	            </a> |
                <a target="_blank" href="{% static "http://app.jd.com/" %}">
	                手机京东
	            </a> |
                <a target="_blank" href="{% static "http://club.jd.com/links.aspx" %}">
	                友情链接
	            </a> |
                <a target="_blank" href="{% static "http://cps.jd.com/" %}">
	                销售联盟
	            </a> |
                <a href="{% static "http://club.jd.com/" %}" target="_blank">
	                京东社区
	            </a> |
                <a href="{% static "http://gongyi.jd.com" %}" target="_blank">
	                京东公益
	            </a> |
                <a target="_blank" href="{% static "http://en.jd.com/" %}" style="width:86px;">English Site</a>
            </div>
            <div class="copyright">
                Copyright&copy;2004-2015&nbsp;&nbsp;京东JD.com&nbsp;版权所有
            </div>
        </div>
    </div>
</body>

</html>

templates/register.html
<!--作者：徐开明-->
<!DOCTYPE html>
<html lang="zh-cn">
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>京东(JD.COM)-综合网购首选-正品低价、品质保障、配送及时、轻松购物！</title>
    <link rel="icon" href="{% static "images/index/favicon.ico" %}" mce_href="{% static "images/index/favicon.ico" %}" type="image/x-icon">
    <meta name="description" content="京东JD.COM-专业的综合网上购物商城,销售家电、数码通讯、电脑、家居百货、服装服饰、母婴、图书、食品等数万个品牌优质商品.便捷、诚信的服务，为您提供愉悦的网上购物体验!">
    <meta name="Keywords" content="网上购物,网上商城,手机,笔记本,电脑,MP3,CD,VCD,DV,相机,数码,配件,手表,存储卡,京东">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" href="{% static "css/register.css" %}">
    <script src="{% static "js/jquery/jquery-1.11.3.min.js" %}"></script>
    <script src="{% static "js/register.js" %}"></script>
</head>

<body>
    <div id="shortcut-2013">
        <div class="w">
            <ul class="fl lh">
                <li class="fore1 ld"><b></b><a href="javascript:addToFavorite()" rel="nofollow">收藏京东</a></li>
            </ul>
            <ul class="fr lh">
                <li class="fore1" id="loginbar"><a href="javascript:login();" class="link-login">你好，请登录</a>&nbsp;&nbsp;<a href="javascript:regist();" class="link-regist style-red">免费注册</a></li>
                <li class="fore2 ld">
                    <s></s>
                    <a href="{% static "http://jd2008.jd.com/JdHome/OrderList.aspx" %}" rel="nofollow">我的订单</a>
                </li>
                <li class="fore3 ld">
                    <s></s>
                    <a href="{% static "http://app.jd.com/" %}" target="_blank">手机京东</a>
                </li>
                <li class="fore4 ld menu" id="biz-service" data-widget="dropdown">
                    <s></s>
                    <span class="outline"></span>
                    <span class="blank"></span> 客户服务
                    <b></b>
                    <div class="dd">
                        <div><a href="{% static "http://help.jd.com/help/question-61.html" %}" target="_blank">常见问题</a></div>
                        <div><a href="{% static "http://myjd.jd.com/repair/orderlist.action" %}" target="_blank" rel="nofollow">售后服务</a>
                        </div>
                        <div><a href="{% static "http://chat.jd.com/jdchat/custom.action" %}" target="_blank" rel="nofollow">在线客服</a></div>
                        <div><a href="{% static "http://myjd.jd.com/opinion/list.action" %}" target="_blank" rel="nofollow">投诉中心</a></div>
                        <div><a href="{% static "http://www.jd.com/contact/service.html" %}" target="_blank">客服邮箱</a></div>
                    </div>
                </li>
                <li class="fore5 ld menu" id="site-nav" data-widget="dropdown">
                    <s></s>
                    <span class="outline"></span>
                    <span class="blank"></span> 网站导航
                    <b></b>
                    <div class="dd lh">
                        <dl class="item fore1">
                            <dt>特色栏目</dt>
                            <dd>
                                <div><a target="_blank" href="{% static "http://my.jd.com/personal/guess.html" %}">为我推荐</a></div>
                                <div><a target="_blank" href="{% static "http://shipingou.jd.com/" %}">视频购物</a></div>
                                <div><a target="_blank" href="{% static "http://club.jd.com/" %}">京东社区</a></div>
                                <div><a target="_blank" href="{% static "http://xiaoyuan.jd.com/" %}">校园频道</a></div>
                                <div><a target="_blank" href="{% static "http://read.jd.com/" %}">在线读书</a></div>
                                <div><a target="_blank" href="{% static "http://diy.jd.com/" %}">装机大师</a></div>
                                <div><a target="_blank" href="{% static "http://market.jd.com/giftcard/" %}">礼品卡</a></div>
                            </dd>
                        </dl>
                        <dl class="item fore2">
                            <dt>企业服务</dt>
                            <dd>
                                <div><a target="_blank" href="{% static "http://market.jd.com/giftcard/company/default.aspx" %}">企业客户</a>
                                </div>
                                <div><a target="_blank" href="{% static "http://sale.jd.com/p10997.html" %}">办公直通车</a></div>
                            </dd>
                        </dl>
                        <dl class="item fore3">
                            <dt>旗下网站</dt>
                            <dd>
                                <div><a target="_blank" href="{% static "http://www.360top.com/" %}">360TOP</a></div>
                                <div><a target="_blank" href="{% static "http://www.minitiao.com/" %}">迷你挑</a></div>
                                <div><a target="_blank" href="{% static "http://en.360buy.com/" %}">English Site</a></div>
                            </dd>
                        </dl>
                    </div>
                </li>
            </ul>
            <span class="clr"></span>
        </div>
    </div>
    <div class="w" id="logo">
        <div>
            <a href="#"><img src="{% static "images/register/logo/logo-2013.png" %}" alt="京东商城" width="170" height="60"></a> <b></b>
        </div>
    </div>
    <div class="w" id="regist">
        <div class="mt">
            <ul class="tab">
                <li class="curr">个人用户</li>
                <li class="line"><a href="#">企业用户</a></li>
                <li class="fore"><a href="#">International Customers</a></li>
            </ul>
            <div class="extra">
                <span style="text-align: right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="flk13" href="#">English</a>
                </span>
                <span>我已经注册，现在就&nbsp;<a href="#" class="flk13">登录</a></span>
            </div>
        </div>
        <div class="mc">
            <form id="personRegForm" method="POST" action="{% url 'user:register' %}">
                <div class="form">
                    <div class="item" id="select-regName">
                        <span class="label">
                            <b class="ftx04">*</b>用户名：
                        </span>
                        <div class="fl item-ifo">
                            <div class="o-intelligent-regName">
                                <input type="text" id="regName" name="username" maxlength="20" class="text">
                                <i class="i-name"></i>
                                <label id="regName_succeed" class="blank"></label>
                                <label id="regName_error"></label>
                            </div>
                        </div>
                    </div>
                    <div id="o-password">
                        <div class="item">
                            <span class="label"><b class="ftx04">*</b>请设置密码：</span>
                            <div class="fl item-ifo">
                                <input type="password" id="pwd" name="password" class="text" tabindex="2">
                                <i class="i-pass"></i>
                                <label id="pwd_succeed" class="blank"></label>
                                <label id="pwd_error"></label>
                                <span class="clr"></span>
                            </div>
                        </div>
                        <div class="item">
                            <span class="label"><b class="ftx04">*</b>请确认密码：</span>
                            <div class="fl item-ifo">
                                <input type="password" id="pwdRepeat" name="password2" maxlength="20" class="text">
                                <i class="i-pass"></i>
                                <label id="pwdRepeat_succeed" class="blank"></label>
                                <label id="pwdRepeat_error"></label>
                            </div>
                        </div>
                        <div class="item" id="dphone">
                            <span class="label"><b class="ftx04">*</b>绑定手机：</span>
                            <div class="fl item-ifo">
                                <input type="text" id="phone" name="mobile" class="text{% if register_form.errors.mobile %} highlight2{% endif %}">
                                <i class="i-phone"></i>
                                <label id="phone_succeed" class="blank"></label>
                                <label id="phone_error2">{% if register_form.errors.mobile %}{% autoescape off %}<span style="color:red">手机格式不对</span>{% endautoescape %}{% endif %}</label>
                            </div>
                        </div>
                        <div id="mobileCodeDiv" class="item " style="height: 62px;">
                            <span class="label"><b class="ftx04">*</b>邮箱：</span>
                            <div class="fl item-ifo">
                                <input type="text" class="text text-1{% if register_form.errors.email %} highlight2{% endif %}" name="email" id="mobileCode">
                                <label class="blank invisible"></label>
                                <label id="phone_error">{% if register_form.errors.email %}{% autoescape off %}<span style="color:red">邮箱格式不对</span>{% endautoescape %}{% endif %}</label>

                                <span class="clr"></span>
                                <div class="msg-text" id="mobileCodeSucMessage"></div>
                                <label id="mobileCode_error" class="blank" style="display: none;"></label>
                                <label id="mobileCode_succeed" class="blank invisible"></label>
                            </div>
                            <span class="clr"></span>
                        </div>

                        <div class="item" id="authcodeDiv">
                            <span class="label"><b class="ftx04">*</b>验证码：</span>
                            <div class="fl item-ifo">
{#                                <input type="text" id="authcode" name="authcode" class="text text-1">#}
{#                                <label class="img">#}
{#                                    <img style="cursor:pointer;width:100px;height:36px;#}
{#                                    display:block;" id="JD_Verification1" src="{% static "images/register/form/image.jpg" %}">#}
{#                                </label>#}
                                {{ register_form.captcha }}
{#                                <label class="ftx23">&nbsp;看不清？#}
{#                                    <a href="javascript:void(0)" class="flk13">换一张</a>#}
{#                                </label>#}
                                <label id="authcode_succeed" class="blank invisible"></label>
                                <span class="clr"></span>
                                <label id="authcode_error"></label>
                            </div>
                        </div>
                    </div>
                    <div class="item item-new">
                        <span class="label">&nbsp;</span>
                        <div class="fl item-ifo">
                            <input type="checkbox" class="checkbox" checked="checked" id="readme">
                            <label for="protocol">我已阅读并同意<a href="#" class="blue" id="protocol">《京东用户注册协议》</a></label>
                            <span class="clr"></span>
                        </div>
                    </div>
                    <div class="item">
                        <span class="label">&nbsp;</span>
                        <input type="submit" class="btn-img btn-regist" id="registsubmit" value="立即注册" tabindex="8">
                    </div>
                </div>
                <div class="phone">
                    <img width="180" height="180" src="{% static "images/register/form/phone-bg.jpg" %}">
                </div>
                <span class="clr"></span>
                {% csrf_token %}
            </form>
        </div>
    </div>
    <div class="w">
        <div id="footer-2013">
            <div class="links">
                <a href="#">关于我们</a>|
                <a href="#">联系我们</a>|
                <a href="#">人才招聘</a>|
                <a href="#">商家入驻</a>|
                <a href="#">广告服务</a>|
                <a href="#">手机京东</a>|
                <a href="#">友情链接</a>|
                <a href="#">销售联盟</a>|
                <a href="#">京东社区</a>|
                <a href="#">京东公益</a>
            </div>
            <div class="copyright">Copyright©2004-2015&nbsp;&nbsp;京东JD.com&nbsp;版权所有</div>
        </div>
    </div>
</body>

</html>